core/impl-base/src/main/java/org/jboss/arquillian/core/impl/ObserverImpl.java
To make it easier to debug on why some method is not
being invoked.
Closes #115.
=> Observer: Emit a warning if any argument is null

build/pom.xml, testng/container/src/main/java/org/jboss/arquillian/testng/container/TestNGTestRunner.java, testng/core/src/test/java/org/jboss/arquillian/testng/TestNGTestBaseClass.java
Updating testNg to use 6.9.10
- Updated TestNG version
- Removed Deprecated code for setAnnotation method.
**Fixes**: #117
=> [ARQ-2058] Updates testNG to use 6.9.10

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/ClientTestInstanceEnricher.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/RunModeUtils.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/execution/ClientBeforeAfterLifecycleEventExecuter.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/execution/ClientTestExecuter.java
The warning is logged only when all following are true:
the test will be run as a client test
the test is NOT marked as a client test
there is defined a deployment in the test case
the deployment the test is tied to is testable
In addition, the warning is logged only when the test is about to be executed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arquillian/arquillian-core/106)
=> ARQ-2012 Limited warnings when test runs as client without @RunAsClient

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/RemoteExtensionLoader.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/loadable/JavaSPIExtensionLoader.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/loadable/LoadableExtensionLoader.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/loadable/ServiceRegistry.java, core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/JavaSPIExtensionLoaderTestCase.java, core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/ServiceRegistryLoaderTestCase.java, core/impl-base/src/test/java/org/jboss/arquillian/core/impl/loadable/ServiceRegistryTestCase.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/ExtensionLoader.java, junit/core/src/test/java/org/jboss/arquillian/junit/rules/RulesEnrichmentTestCase.java
Allow Arquillian Core to define a way to veto services so extensions can control which services are added and which are not allows so they can add their own. Typical example are ResourceProviders.
With Arquillian Extensions you are able to override a service that was previously registered by Arquillian Core or by other extensions. 
The problem is that if if there two extensions that override the same service, it will depend on the order of the registration of the extension that will define which version of the service will be the one used at the end.
To avoid this problem the best way would be to be able to set a priority in extension registry so you can set which one is going to be the last one.
The best none invasive approach we have found is by providing a SPI so any extension can …
=> Adds vetoed feature for services

core/impl-base/src/main/java/org/jboss/arquillian/core/impl/EventContextImpl.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/ManagerImpl.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/RuntimeLogger.java, core/impl-base/src/test/java/org/jboss/arquillian/core/impl/ManagerProcessingTestCase.java
Logs extension registration when debug enabled
When the test is run with a property arquillian.debug then there should be printed a list of all loaded extensions on the stdout.
**Fixes**: https://issues.jboss.org/browse/ARQ-2075
Example of output:
```
(X) org.jboss.arquillian.core.impl.loadable.LoadableExtensionLoader
(E) ManagerProcessing
(O) LoadableExtensionLoader.load
(E) ServiceRegistryLoader
(X) org.arquillian.algeron.pact.consumer.core.PactConsumerConfigurator
(X) org.jboss.arquillian.config.impl.extension.ConfigurationRegistrar
(X) org.arquillian.algeron.pact.consumer.core.client.StandaloneConsumerPactTest
(X) org.arquillian.algeron.consumer.core.AlgeronConsumerConfigurator
(X) org.jboss.arquillian.junit.extension.UpdateTestResultBeforeAfter
(X) …
```
=> Logs extension registration when debug enabled

testenrichers/ejb/src/main/java/org/jboss/arquillian/testenricher/ejb/EJBInjectionEnricher.java, testenrichers/resource/src/main/java/org/jboss/arquillian/testenricher/resource/ResourceInjectionEnricher.java
**Fixes**: https://issues.jboss.org/browse/ARQ-2107 https://issues.jboss.org/browse/ARQ-2109
=> [ARQ-2107][ARQ-2109] improve @EJB and @Resource enrichers

core/impl-base/src/main/java/org/jboss/arquillian/core/impl/ObserverImpl.java
Humans read arguments starting on 1, not 0.
Also, while on it, print the type of the null argument,
to make it easier to identify it.
=> Fix the argument number on observer warning

docs/additional-features.adoc, docs/containers.adoc
Fixes some typos in the documentation
- none
**Fixes**: #
=> Fix typos and phrasing in documentation

docs/additional-features.adoc
docs: fix typos and formatting
**Fixes**: #
=> docs: fix typos and formatting

container/test-api/src/main/java/org/jboss/arquillian/container/test/api/ShouldThrowException.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/AnnotationDeploymentScenarioGenerator.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/client/deployment/AnnotationDeploymentScenarioGeneratorTestCase.java
Makes it so that deployments that throw exceptions can be testable.
- Adding new attribute on ShouldThrowException to indicate that it is testable
- Added new test for the case
Fixes # ARQ-2143
PS - Please give this some love.
=> ARQ-2143 - Allow testable to be overridden when throwing exception.

container/impl-base/src/main/java/org/jboss/arquillian/container/impl/client/deployment/ArchiveDeploymentExporter.java, container/impl-base/src/test/java/org/jboss/arquillian/container/impl/client/deployment/ArchiveDeploymentExporterTestCase.java
Removes exported/exploded directory if present before exporting directory.
- Removes directory if present
- Add unit test.
**Fixes**: #151 (ARQ-2169)
=> fix(ARQ-2169): removes exported directory if exists

junit/core/src/main/java/org/jboss/arquillian/junit/AdaptorManager.java, junit/core/src/main/java/org/jboss/arquillian/junit/AdaptorManagerWithNotifier.java, junit/core/src/main/java/org/jboss/arquillian/junit/Arquillian.java, junit/core/src/main/java/org/jboss/arquillian/junit/ArquillianTest.java, junit/core/src/main/java/org/jboss/arquillian/junit/ArquillianTestClass.java, junit/core/src/main/java/org/jboss/arquillian/junit/ArquillianTestClassLifecycleManager.java, junit/core/src/main/java/org/jboss/arquillian/junit/MethodInvoker.java
The code of the `TestRunnerAdaptor` management is same in both JUnit runner and JUnit class rule. The same can be also applied to the logic that invokes the test method. 
I've moved the code to separated classes that are used by both implementations. As a benefit:
* we don't duplicate the code
* it is guaranteed that when the code is changed, it will affect both implementations.
When I was doing the refactoring, I've noticed that in the rule implementations there was missing enrichment of the other rules used in the test class:
```java
adaptor.fireCustomLifecycle(new RulesEnrichment(target, testClass, testMethod, LifecycleMethodExecutor.NO_OP));
```
So I added it there.
=> chore(ARQ-2172): merged the same runner and rule code to avoid code duplication

README.adoc, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGenerator.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGeneratorTestCase.java, core/api/src/main/java/org/jboss/arquillian/core/api/annotation/Observer.java, core/impl-base/src/main/java/org/jboss/arquillian/core/impl/ManagerImpl.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/Manager.java, docs/advanced-topics.adoc, test/impl-base/src/main/java/org/jboss/arquillian/test/impl/EventTestRunnerAdaptor.java, test/impl-base/src/test/java/org/jboss/arquillian/test/impl/AdditionalTestClassObserverTestCase.java
In case a user needs to observe one or more Arquillian events and he doesn't want to deal with the whole SPI machinery (to create a new Arquillian extension), then it is  possible to use a new annotation `@Observer` at the test class and observe any Arquillian event in the context of the related test class that he need (starting with `BeforeClass` and ending with `AfterClass`):
=> feat(ARQ-2174): Added Observer annotation for specifying an Arquillian observer  for the given test class

container/impl-base/src/main/java/org/jboss/arquillian/container/impl/client/container/DeploymentExceptionHandler.java, container/impl-base/src/test/java/org/jboss/arquillian/container/impl/client/container/DeploymentExceptionHandlerTestCase.java
…returns null."
Issue link - https://issues.jboss.org/browse/ARQ-2175
Fixes possible `null` value handed over to exception transformers.
`DeploymentExceptionHandler` should never pass `null` value to transformers.
This is a possible scenario when the exception in question is `DeploymentException` and when it has either no cause set or the cause is itself (is which case `getCause()` returns null).
Test attached.
@MatousJobanek I find this to be the least painful solution to the issue we discussed earlier. Please review.
=> fix(ARQ-2175): exception handling in case DeploymentException.getCause

config/impl-base/src/main/java/org/jboss/arquillian/config/impl/extension/ConfigurationRegistrar.java
Exposes Arquillian Descriptor to extract extension configuration in Arquillian Cube. 
- refactors `loadConfiguration()` to expose `Arquillian Descriptor`
Fixes https://github.com/arquillian/arquillian-cube/issues/984
=> chore: exposes Arquillian Descriptor to be used in extensions. 

container/test-spi/src/main/java/org/jboss/arquillian/container/test/spi/RemoteLoadableExtension.java, core/api/src/main/java/org/jboss/arquillian/core/api/Instance.java, core/api/src/main/java/org/jboss/arquillian/core/api/InstanceProducer.java, core/api/src/main/java/org/jboss/arquillian/core/api/annotation/Inject.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/LoadableExtension.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/ServiceLoader.java
This documentation could have potentially saved me hours when I was first writing an Arquillian extension - you assume the injection framework is going to work like any other, where you bind components either using annotations or some module API (which is what the loadable extension API looks like with its service registration method), and even though through reverse engineering I'd worked out that components could be provided by `InstanceProducer.set()`, it never occurred to me that that was an API that I was supposed to use, I thought that was an internal implementation detail that Arquillian would invoke, for example, for each service registered by a loadable extension. So I spent hours scratching my head trying to understand why the services I had registered weren't being injected, …
=> Added javadocs for injection and extensions

testng/container/src/main/java/org/jboss/arquillian/testng/container/TestNGTestRunner.java
I would like to propose a fix for a problem that when there is a runtime exception or error while running runner.run() method in TestNGRunner, the problem is ignored.
If someone omits required runtime class in a deployment archive there will be ClassDefNotFoundError when executing run() method in TestNGRunner. Arquillian servlet will return HTTP code 500 which is ignored in servlet protocol runner and consequently returned as a test which passed. But in reality the test did not even run and should be marked as failed.
I propose a fix which catches runtime exceptions and errors while executing runner.run() method and envelope it in TestResult.failed() so it is reported as failed test.
=> Fix for ignored runtime exception in runner.run() method

container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/ContainerEventControllerTestCase.java, junit/core/src/main/java/org/jboss/arquillian/junit/MethodInvoker.java, protocols/jmx/src/main/java/org/jboss/arquillian/protocol/jmx/JMXMethodExecutor.java, protocols/jmx/src/test/java/org/jboss/arquillian/protocol/jmx/JMXTestRunnerTestCase.java, protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/AbstractServerBase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ProtocolTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/test/MockTestRunner.java, test/spi/src/main/java/org/jboss/arquillian/test/spi/TestMethodExecutor.java, testng/core/src/main/java/org/jboss/arquillian/testng/Arquillian.java
This resolves #214 by adding support for JUnit compatible testing frameworks for which `FrameworkMethod.getName()` != `FrameworkMethod.getMethod().getName()` and which allow test method names with reserved url characters.
- Use the logical and not the actual test method name in `ServletMethodExecutor`
- Escape reserved characters in test method names when composing urls in `ServletMethodExecutor`
I understand that this fixes two separate issues but I decided to submit fixes for them as a single PR because I believe that are interrelated. Please let me know if you'd like to have this split into two commits and two PRs.
I believe that changes made are backwards compatible with the only problematic one in my opinion being introduction of `TestMethodExecutor.getMethodName()`. Ideally it would …
=> fix: improves method name handling executors

.travis.yml, bom/pom.xml
=> fix: bumps resolver to 3.1.4 using HTTPS for mvn central

bom/pom.xml
TestNG 7 support has been added in #232. This PR adds the new artifacts to the bom.
Add the new TestNG 7 artifacts to the bom.
=> fix: adds TestNG7 to bom

container/spi/src/main/java/org/jboss/arquillian/container/spi/client/deployment/Deployment.java
We use an event observer to give detailed error messages to our developers when an Arquillian deployment fails, as some of the errors specific to our project may be somewhat misleading and lead them to conclude that the test setup is broken, when it is in fact their local settings. To do this, we need to analyze the exception stored in the Deployment object.
Currently, we are using reflection to get at this field, but a simple getter is much more desirable.
- Exposes the field deploymentError in Deployment using a getter
=> feat: exposes deploymentError in Deployment

test/impl-base/src/test/java/org/jboss/arquillian/test/impl/enricher/resource/ArquillianResourceTestEnricherTestCase.java
Unit test ArquillianResourceTestEnricherTestCase.shouldBeAbleToThrowExceptionWithMultipleResourceProvidersWhichProvidesNullLookUp() does not pass on non-english systems.
It checks that the log contains strings like "WARNING: xxx", but this "WARNING" is translated on non-english systems. For exemple, on my computer the log messages are:
> AVERTISSEMENT: Provider for type class java.lang.Object returned a null value: resourceProvider
This PR removes the "WARNING" words from the checks.
=> fix: unit test shouldn't rely on localized strings

build/pom.xml, testng/core/src/main/java/org/jboss/arquillian/testng/Arquillian.java
I've just realized I made a stupid and embarrassing error in my previous commit related to testng7 support.
When running tests using testng7, a runtime exception is generated that makes all tests pass (that's why I thought my previous PR was working) without even being executed!! :-(
This new PR fixes this (very annoying) problem.
I'm really sorry for that.
=> fix: fixes testng7 support

README.adoc
Issue: https://issues.redhat.com/browse/ARQ-2207
Description: The Issue Tracker link provided inside README.adoc of arquillian/arquillian-core need to replace with the new one.
=> doc(ARQ-2207): updates the links in README

junit5/container/src/main/java/org/jboss/arquillian/junit5/container/JUnitJupiterTestRunner.java
When testing my project with JUnit 5, I get `ClassCastException` instead of test result
Full stack trace is here: https://github.com/arquillian/arquillian-core/issues/137#issuecomment-725028937
Relates to #137
=> fix(junit5): ClassCastException when filtering test methods

bom/pom.xml
There appears to be a duplicate entry for `version.shrinkwrap_resolver` in bom/pom.xml.
=> fix: removes duplicate "version.shrinkwrap_resolver"

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/AbstractDeploymentScenarioGenerator.java
It seems to me that there is possibility to create valid deployment without the archive (f.e. with only descriptor). In such case this check will always fail with NullPointerException.
=> fix: skips deployment validation if not present

junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java
- @BeforeAll / @AfterAll callbacks are always called on the client, consistent with JUnit 4 behavior
- restored calls to @BeforeEach / @AfterEach in client mode, were only being called on the server
Fixes problems encountered in #288 and #301
Fixes #309
=> fix: aligns lifecycle calls in JUnit 5 with JUnit 4 behavior

README.adoc, junit5/container/pom.xml, junit5/container/src/main/java/org/jboss/arquillian/junit5/container/JUnitJupiterTestRunner.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/ClassWithArquillianExtensionWithExtensions.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitIntegrationTestCase.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitJupiterDeploymentAppenderTestCase.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitJupiterTestRunnerTestCase.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitTestBaseClass.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/TestScenarios.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/IdentifiedTestException.java
After merging the PR for #301 there is a new issue as described in #309. This could have been avoided if we had (more) tests in the new junit5 module. 
With this PR I tried to convert the existing tests for JUnit4 in arquillian-junit-container to arquillian-junit5-container. I'm not sure if they are all useful, and I needed to adapt and delete some. But at least the issue with the lifecycle methods is detected by a test failure, and the fix provided by @lprimak in #310 makes them green again.
=> chore(junit5): ports tests from arquillian-junit-container

protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/ServletMethodExecutor.java, protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/ServletMethodExecutor.java
Fixes #319 
added locks and signalling to correctly cancel timers so no stale ope…rations
are called to undeployed applications
=> fix(jakarta): introduces locks to avoid race conditions

build/pom.xml, config/impl-base/pom.xml, container/impl-base/pom.xml, container/impl-base/src/test/java/org/jboss/arquillian/container/impl/client/container/ContainerDeployControllerTestCase.java, container/test-impl-base/pom.xml, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/client/deployment/ClientDeployerTestCase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/domain/ProtocolRegistryTestCase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/enricher/resource/InitialContextProviderTestCase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/enricher/resource/OperatesOnDeploymentAwareProviderBase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProviderTestCase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/execution/LocalTestExecuterTestCase.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/execution/RemoteTestExecuterTestCase.java, junit/container/pom.xml, junit/core/pom.xml, junit/standalone/pom.xml, junit5/container/pom.xml, pom.xml, test/impl-base/pom.xml, test/impl-base/src/test/java/org/jboss/arquillian/test/impl/EventTestRunnerAdaptorTestCase.java, test/impl-base/src/test/java/org/jboss/arquillian/test/impl/enricher/resource/ArquillianResourceTestEnricherTestCase.java, testng/core/pom.xml
This PR solves https://github.com/arquillian/arquillian-core/issues/364
- Bump java version from 1.6 to 1.8
- Remove mockito-all that is not maintained and use mockito-core
- Remove unused stubbing.
Fixes #364
=> refactor: migrates to mockito-core and enforces jdk8 bytecode

container/spi/src/main/java/org/jboss/arquillian/container/spi/client/container/DeployableContainer.java
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
Default methods for the DeployableContainer interface
The DeployableContainer contains two methods that are never used: 
- void deploy(Descriptor descriptor)
- void undeploy(Descriptor descriptor)
Providing noop default methods for these reduces some of the noise in especially small implementations.
The interface also contains methods that are not always uses:
- void setup(T configuration)
- void start()
- void stop()
For instance, some embedded implementations don't have an explicit start/stop step. They start/stop implicitly with deploy/undeploy.
=> feat: provides default implementations for DeployableContainer

protocols/pom.xml, protocols/rest-jakarta/README.adoc, protocols/rest-jakarta/pom.xml, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/REST3Extension.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/RESTDeploymentAppender.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/RESTDeploymentPackager.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/RESTMethodExecutor.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/RESTProtocol.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/RESTURIHandler.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTCommandService.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTProtocolApplication.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTRemoteExtension.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTTestRunner.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/SecurityActions.java, protocols/rest-jakarta/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/AbstractServerBase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/BaseRESTProtocolTestCase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/ProtocolDeploymentAppenderTestCase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/ProtocolTestCase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/RESTCommandServiceTestCase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/RESTDeploymentPackagerTestCase.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/TestUtil.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/test/MockTestRunner.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/test/TestCommandCallback.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/test/TestIntegerCommand.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/test/TestStringCommand.java, protocols/rest-jakarta/src/test/resources/META-INF/services/org.jboss.arquillian.container.test.spi.TestRunner
Today arquillian has a servlet dependency in order to run a test on the application server.  To test functions like CDI and RESTful Web Services that do not require servlet, this is not suitable since MicroProfile and now Core Profile in Jakarta EE 10 do not require the application server to expose servlet API and function in applications.  This PR provides a way to run a test on a server that does not have servlet enabled by using a RESTful Web Services resource instead. 
- Create a RESTful Web Services arquillian protocol so do not need to depend on servlet in an application server in order to run tests on the server.
- Duplicate the servlet-jakarta tests in the rest protocol project and update them to test the REST protocol
Fixes #408
=> Add a REST protocol option to not depend on servlet to run tests

pom.xml
* updates maven-javadoc-plugin to latest 3.4.0
* swaps UML doclet to alternative working with latest JDKs
* removes jboss-compiler overwrite as it's been fixed
Fixes #414
=> fix(release): changes javadoc settings for JDK 11+

bom/pom.xml
The bom does not include the new protocol-rest-jakarta project.
- Add protocol-rest-jakarta artifact to the bom.
Fixes #418
=> fix (release): Update bom to include new protocol-rest-jakarta artifact

container/spi/src/main/java/org/jboss/arquillian/container/spi/client/protocol/metadata/HTTPContext.java, container/spi/src/main/java/org/jboss/arquillian/container/spi/client/protocol/metadata/Servlet.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProvider.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProviderTestCase.java
…ps should be used.
Adds the ability to allow for https URL and URI injection.
- Add a `isSecure()` method to the `HTTPContext`
- Allow the `Servlet` to use the correct protocol
Fixes #422
=> feat: enables HTTPContext to indicate if HTTPS should be used

protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTProtocolApplication.java, protocols/rest-jakarta/src/main/java/org/jboss/arquillian/protocol/rest/runner/RESTTestRunner.java, protocols/rest-jakarta/src/test/java/org/jboss/arquillian/protocol/rest/AbstractServerBase.java
When an application has a REST Application with an ApplicationPath of /, the rest-jakarta conflicts with it causing 404 errors because only one Application starts.
- Switch @ApplicationPath and @Path path values.
Fixes #436
=> fix(protocols):  Fix rest-jakarta protocol to not conflict with other REST Applications in war file

testng/core/src/main/java/org/jboss/arquillian/testng/Arquillian.java
fixes https://github.com/arquillian/arquillian-core/issues/427
fixes https://github.com/flowlogix/test-arq-suite/pull/49
Short description of what this resolves:
After upgrading to TestNG 7.6.1+ Arquillian no longer works
Changes proposed in this pull request:
Sets status for TestNG tests when tests succeed, fail or skipped.
Previously TestNG status was only set on failure
=> fix: propagates failures with TestNG 7.6.1+

protocols/servlet-jakarta/README.adoc, protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/Servlet5Extension.java, protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/ServletExtension.java, protocols/servlet-jakarta/src/main/java/org/jboss/arquillian/protocol/servlet5/v_6/ServletProtocol.java, protocols/servlet-jakarta/src/main/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
As a part of [Adaptation to Jakarta EE 10](https://github.com/arquillian/arquillian-core/issues/444) this PR adds new protocol - Servlet 6.0
=> feat: introduces jakarta servlet 6.0 protocol module

testng/container/src/main/java/org/jboss/arquillian/testng/container/TestNGDeploymentAppender.java
I encounter a `java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory` when I use `TestNG` 7.5+ version. TestNG requires slf4j package however the target container (Payara-Micro) does not have it
- Update TestNG Auxilliary Appender to add org.slf4j package
https://github.com/arieki/arquillian-reproducer
=> Fixed slf4j NoClassDefFoundError for TestNG 7.5+ Used in Target Container 

.mvn/maven.config, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProvider.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/enricher/resource/URLResourceProviderTestCase.java, test/api/src/main/java/org/jboss/arquillian/test/api/Secured.java
Replaces out of date #43 and it a minor edit of @samaxes work
Signed-off-by: Scott M Stark <starksm64@gmail.com>
Signed-off-by: samaxes
Add support for injecting https URLs
Add https scheme and port support to URLResourceProvider for use with @ArquillianResource and @Secured
Fixes #
[ARQ-1321]
=> [ARQ-1321] Support for HTTPS in URLs injected with @ArquillianResource

build/pom.xml, junit5/container/pom.xml, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/ClassWithArquillianExtensionAndParameterizedTest.java, junit5/container/src/test/java/org/jboss/arquillian/junit5/container/JUnitParameterizedTestCase.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java
Fixes https://github.com/arquillian/arquillian-core/issues/504
Fixes an issue where *parameterized* tests are reported as passed, even if they failed.
- Call `ExceptionUtils::throwAsUncheckedException()` in the `ArquillianExtension#interceptTestTemplateMethod()` method even if the invocation is `RunAsClient`.
For a test case:
- Added dependency on junit-jupiter-params JAR, to make the `@ParameterizedTest` annotation available.
- Added a test case.
=> Failure of parameterized test is not reported as a failure

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/RemoteExtensionLoader.java
This problem was found as part of https://github.com/arquillian/arquillian-extension-warp/issues/131 - full details see there.
When deploying a test using arquillian-extension-warp to GlassFish 4.1 or newer **running on a Windows machine** (no problem on linux), all Jars that are inside "WEB-INF\lib" of the deployed app are locked and the app has a long delay until GlassFish performs the "undeploy" operation.
Using [File Leak Detector](https://github.com/jenkinsci/lib-file-leak-detector/), I found that `org.jboss.arquillian.container.test.impl.RemoteExtensionLoader` is one of the culprits for this leak: `URL.openStream` creates a `java.net.JarConnection` that caches opened files by default.
As those files are accessed only once in Arquillian, there is no performance reason to cache them. …
=> Avoid file leak in RemoteExtensionLoader

protocols/servlet/pom.xml, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/AbstractServerBase.java
Jetty 8.1.2.v20120308 bypass vulnerability
- Upgrade to the Jetty 9.4.51.v20230217 version that includes the fix
- Update how the base URI obtains the connector server port for changes in Jetty 9
-
Fixes #
Replaces the #485 PR which does not compile
=> Fix for the Jetty bypass vulnerability fixed in version 9.4.51.v20230217

protocols/servlet-jakarta/src/test/java/org/jboss/arquillian/protocol/servlet5/v_5/ServletProtocolDeploymentPackagerTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/v_2_5/ServletProtocolDeploymentPackagerTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/v_3/ServletProtocolDeploymentPackagerTestCase.java, testenrichers/cdi-jakarta/src/test/java/org/jboss/arquillian/testenricher/cdi/BeansXMLProtocolProcessorTestCase.java, testenrichers/cdi/src/test/java/org/jboss/arquillian/testenricher/cdi/BeansXMLProtocolProcessorTestCase.java
replace it with the other constructor: 
```
TestDeployment(
org.jboss.arquillian.container.spi.client.deployment.DeploymentDescription, 
org.jboss.shrinkwrap.api.Archive<?>, 
java.util.Collection<org.jboss.shrinkwrap.api.Archive<?>>
)
```
=> chore: replace deprecated org.jboss.arquillian.container.test.spi.TestDeployment constructor

config/impl-base/src/test/java/org/jboss/arquillian/config/impl/extension/PropertiesParserTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/BaseServletProtocolTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/ServletCommandServiceTestCase.java, protocols/servlet/src/test/java/org/jboss/arquillian/protocol/servlet/v_2_5/ServletProtocolDeploymentPackagerTestCase.java
Add exceptional tests to existing test files. See [issue](https://github.com/arquillian/arquillian-core/issues/542#issue-2186940428)
- 9 new exceptional tests
-
-
Fixes #542
=> Add 9 new exceptional tests

protocols/servlet/src/main/java/org/jboss/arquillian/protocol/servlet/runner/ServletTestRunner.java
If `response.sendError` fails the first exception `e` will be lost entirely and all the developer will see is the reason why `response.sendError`failed. A small change will ensure the data from `e` and `e2` are both available when looking at server log files.
- A simple addSuppresed statement to prevent a useful exception from being unreported
=> preserve first exception in writeObject

container/impl-base/src/main/java/org/jboss/arquillian/container/impl/ContainerImpl.java, container/impl-base/src/test/java/org/jboss/arquillian/container/impl/ContainerRegistryTestCase.java, container/spi/src/main/java/org/jboss/arquillian/container/spi/Container.java, container/spi/src/main/java/org/jboss/arquillian/container/spi/client/container/ConfigurationMapper.java, container/spi/src/main/java/org/jboss/arquillian/container/spi/client/container/DeployableContainer.java
…
Fixes #552
This addresses #552 
- Add a new ConfigurationMapper interface that is returned from DeployableContainer
- Improve the ContainerConfiguration generic type usage to avoid casts
- Add test showing mapping of String property def to String[] in a CustomContainerConfiguration
=> Add support for specifying a custom mapper implementation for a DeployableContainer.

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGenerator.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGeneratorTestCase.java, container/test-spi/src/main/java/org/jboss/arquillian/container/test/spi/TestDeployment.java
=> Enable access to the ProtocolConfiguration info from the TestDeployment.

testenrichers/cdi/pom.xml
The CDIInjectionEnricherTestCase relies on Weld being able to make protected/private fields accessible. This requires additional access permissions when running under Java SE 17+
Add an override to the surefire plugin configuration to include a `--add-opens java.base/java.lang=ALL-UNNAMED`
Fixes #564
=> Add --add-opens to surefire for running tests on Java SE 17+

junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java, test/spi/src/main/java/org/jboss/arquillian/test/spi/LifecycleMethodExecutor.java
https://issues.redhat.com/browse/ARQ-2231
=> ARQ-2231 The JUnit 5 container does not work with manual mode tests

.github/workflows/ci.yml
Follow up on https://github.com/arquillian/arquillian-core/pull/565 - we can now run tests with JDK 17.
=> CI: add JDK 17 testing; run CI on all branches; cleanup ci.yml.

.github/workflows/ci.yml
=> CI: add JDK 21 (LTS) to testing matrix.

container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/ContainerTestExtension.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/AnnotationDeploymentScenarioGenerator.java, container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/execution/LocalTestExecuter.java, container/test-impl-base/src/test/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGeneratorTestCase.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/LoadableExtension.java, junit/standalone/src/main/java/org/jboss/arquillian/junit/standalone/LocalTestMethodExecutor.java, test/spi/src/main/java/org/jboss/arquillian/test/spi/execution/ExecUtils.java, testng/standalone/src/main/java/org/jboss/arquillian/testng/standalone/LocalTestMethodExecutor.java
Add support for `@ArquillianResource` param injection on `@Deployment` methods
Aggregate the `TestEnricher` argument generation into a single util class
Improve some of the javadoc
Fixes #601
=> Add support for ArquillianResource param injection on @Deployment methods

core/impl-base/src/main/java/org/jboss/arquillian/core/impl/ManagerImpl.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/ArquillianThreadLocal.java, core/spi/src/main/java/org/jboss/arquillian/core/spi/context/AbstractContext.java
This is another attempt to work around the ThreadLocal memory leak that happens in arquillian-extension-warp. The first pull request #501 fails on Java 11 and was reverted by #579 (issue #578).
I replaced ThreadLocal with a `Hashtable<Long, T>` inside a utility class, where the key is the thread id. This way, it is easy to cleanup the full cache, which is done in `ManagerImpl` and `AbstractContext`.
What do you think? Is this an approach that could work? Or do I have a basic misunderstanding about ThreadLocals or did I break something else?
At least I could run the arquillian-extension-warp testsuite against a remote WildFly server ten times without OutOfMemoryException, while it failed before after 5-7 runs.
=> Replace ThreadLocal with a hashtable to support reliable cleanup

integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/lifecycle/FileWriterExtension.java, integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/lifecycle/Greeter.java, integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/lifecycle/LifecycleMethodsTest.java, integration-tests/pom.xml
Integration tests for lifecycle methods with JUnit 5
Relates to #310 #309 and #301
using `@TempDir` as a base for temporary directory
Could not use it 'as is' because it gets deleted for each test class,
but the files need to be kept throughout the test suite
<!-- 
Many thanks for contributing to Arquillian! Together we can make the testing world better.
Please tell us what this PR brings following the template we provided. 
And don't forget to link to the issue (or create one if there is none).
If you are still working on the change please prefix this pull request title with "WIP"
=> Added integration tests for JUnit 5 lifecycle methods

integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/resource/injection/AbstractArquillianResourceTest.java, integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/resource/injection/ClientArquillianResourceTest.java, integration-tests/junit5-tests/src/test/java/org/jboss/arquillian/integration/test/resource/injection/InContainerArquillianResourceTest.java, integration-tests/pom.xml, junit5/container/src/main/java/org/jboss/arquillian/junit5/container/JUnitJupiterDeploymentAppender.java, junit5/container/src/main/java/org/jboss/arquillian/junit5/container/JUnitJupiterRemoteExtension.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/ArquillianExtension.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/ContextStore.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/MethodParameterObserver.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/MethodParameterProducerEvent.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/MethodParameters.java, junit5/core/src/main/java/org/jboss/arquillian/junit5/extension/JUnitJupiterCoreExtension.java
Allows method parameters which are provided by Arquillian to be injected. The parameters are resolved from `TestEnricher`'s. 
Note that for in-container tests, a `ParameterResolver` outside of Arquillian does not work. In other words, you can't inject a method parameter like `@TempDir final Path path` because two resolvers will be found. One being the real resolver, the other being the `ArquillianExtension`. This seems to be due to the fact that the parameter resolver is executed twice for in-container tests. Once for invoking the test from client and once executing in the container itself.
To work around the above, I created a `@Vetoed` annotation which can be set on those parameters to allow Arquillian to ignore them. Note I don't know if using the same name as the CDI annotation is …
=> [312] Initial attempt to allow Arquillian to inject method parameters.

junit5/core/src/main/java/org/jboss/arquillian/junit5/IdentifiedTestException.java, test/spi/README.md, test/spi/pom.xml, test/spi/src/main/java/org/jboss/arquillian/test/spi/ArquillianProxyException.java, test/spi/src/main/java/org/jboss/arquillian/test/spi/ExceptionProxy.java, test/spi/src/test/java/org/jboss/arquillian/test/spi/ExceptionProxyTestCase.java, test/spi/src/test/java/org/jboss/arquillian/test/spi/IBean.java, test/spi/src/test/java/org/jboss/arquillian/test/spi/IException.java, test/spi/src/test/java/org/jboss/arquillian/test/spi/serveronly/SomeBean.java, test/spi/src/test/java/org/jboss/arquillian/test/spi/serveronly/SomeNonClientSideException.java
This is a first step that preserves the current unit tests, but I think we need to be more aggressive at restoring the original exception from the type hierarchy and almost never actually see an `ArquillianProxyException`.  The only time it would be seen is if none of the exception types could be loaded on the client.
Fixes #641
=> Improve the handling of exception propagation

core/impl-base/src/main/java/org/jboss/arquillian/core/impl/loadable/JavaSPIExtensionLoader.java
This is the same that was already done for RemoteExtensionLoader in #502: when running the test suite for https://github.com/arquillian/arquillian-extension-warp with the Glassfish profile (Glassfish 7.0.18), on windows there are file leaks that cause every test to take 20 seconds. Reason: Glassfish cannnot delete "arquillian-core.jar" on undeploy.
Using [File Leak Detector](https://github.com/jenkinsci/lib-file-leak-detector/), I found that org.jboss.arquillian.container.test.impl.RemoteExtensionLoader is the culprit for this leak: `URL.openStream` creates a `java.net.JarConnection` that caches opened files by default.
As those files are accessed only once in Arquillian, there is no performance reason to cache them.
This pull request switches off caching.
WildFly is not affected by this …
=> Avoid file leak in JavaSPIExtensionLoader

junit5/core/src/main/java/org/jboss/arquillian/junit5/MethodParameterObserver.java
This resolves #688: in the arquillian-extension-warp test suite, there is a TestEnricher implementation whose `resolve` returns null. This causes an exception with arquillian 1.9.2. So this commit adds a null check.
According to the comments of `TestEnricher.resolve`, I am not sure whether null is a allowed return value.  But the code in `org.jboss.arquillian.test.spi.execution.ExecUtils.enrichArguments` also checks for null.
=> MethodParameterObserver.injectParameters: handle null result of TestEnricher.resolve
